// joint_names.h
#ifndef JOINT_NAMES_H
#define JOINT_NAMES_H

typedef enum {
    THUMB_DISTAL,
    THUMB_MIDDLE,
    THUMB_METACARPAL,
    INDEX_DISTAL,
    INDEX_MIDDLE,
    INDEX_PROXIMAL,
    INDEX_METACARPAL,
    MIDDLE_DISTAL,
    MIDDLE_MIDDLE,
    MIDDLE_PROXIMAL,
    MIDDLE_METACARPAL,
    RING_DISTAL,
    RING_MIDDLE,
    RING_PROXIMAL,
    RING_METACARPAL,
    PINKY_DISTAL,
    PINKY_MIDDLE,
    PINKY_PROXIMAL,
    PINKY_METACARPAL,
    WRIST_WAVE,
    WRIST_FLICK,
    WRIST_NAE_NAE,
    ELBOW,
    BICEP,
    SHOULDER_FRONT_RAISE,
    SHOULDER_LAT_RAISE,
    NUM_OF_JOINTS,
} joint_e;

#endif